### ISSUE TITLE
refactor tests

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eokson#6]

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#10](https://github.com/eo-cqrs/eokson/issues/10), [#9](https://github.com/eo-cqrs/eokson/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#10](https://github.com/eo-cqrs/eokson/issues/10), [#22](https://github.com/eo-cqrs/eokson/issues/22), [#9](https://github.com/eo-cqrs/eokson/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#10](https://github.com/eo-cqrs/eokson/issues/10), [#9](https://github.com/eo-cqrs/eokson/issues/9) are still not solved; solved: [#22](https://github.com/eo-cqrs/eokson/issues/22).

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#10](https://github.com/eo-cqrs/eokson/issues/10), [#29](https://github.com/eo-cqrs/eokson/issues/29), [#9](https://github.com/eo-cqrs/eokson/issues/9) are still not solved; solved: [#22](https://github.com/eo-cqrs/eokson/issues/22).

**Comment by h1alexbel** [comment]
@zoeself register

**Comment by zoeself** [comment]
> @zoeself register

@h1alexbel I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#10](https://github.com/eo-cqrs/eokson/issues/10) is still not solved; solved: [#22](https://github.com/eo-cqrs/eokson/issues/22), [#29](https://github.com/eo-cqrs/eokson/issues/29), [#9](https://github.com/eo-cqrs/eokson/issues/9).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#47](https://github.com/eo-cqrs/eokson/issues/47) is still not solved; solved: [#10](https://github.com/eo-cqrs/eokson/issues/10), [#22](https://github.com/eo-cqrs/eokson/issues/22), [#29](https://github.com/eo-cqrs/eokson/issues/29), [#9](https://github.com/eo-cqrs/eokson/issues/9).
